In [9]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/1sgMbcgoOGEDSWu3MDrIcoADW59HZU4ujoLgNBUZJVXg/export?format=csv"
data = pd.read_csv(url)

display(data)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [10]:
selected_data = data[["FIRST_NAME", "LAST_NAME","EMAIL"]]
print(selected_data)

     FIRST_NAME    LAST_NAME     EMAIL
0        Donald     OConnell  DOCONNEL
1       Douglas        Grant    DGRANT
2      Jennifer       Whalen   JWHALEN
3       Michael    Hartstein  MHARTSTE
4           Pat          Fay      PFAY
5         Susan       Mavris   SMAVRIS
6       Hermann         Baer     HBAER
7       Shelley      Higgins  SHIGGINS
8       William        Gietz    WGIETZ
9        Steven         King     SKING
10        Neena      Kochhar  NKOCHHAR
11          Lex      De Haan   LDEHAAN
12    Alexander       Hunold   AHUNOLD
13        Bruce        Ernst    BERNST
14        David       Austin   DAUSTIN
15        Valli    Pataballa  VPATABAL
16        Diana      Lorentz  DLORENTZ
17        Nancy    Greenberg  NGREENBE
18       Daniel       Faviet   DFAVIET
19         John         Chen     JCHEN
20       Ismael      Sciarra  ISCIARRA
21  Jose Manuel        Urman   JMURMAN
22         Luis         Popp     LPOPP
23          Den     Raphaely  DRAPHEAL
24    Alexander         Khoo     AKHOO
25       Shelli        Baida    SBAIDA
26        Sigal       Tobias   STOBIAS
27          Guy       Himuro   GHIMURO
28        Karen   Colmenares  KCOLMENA
29      Matthew        Weiss    MWEISS
30         Adam        Fripp    AFRIPP
31        Payam     Kaufling  PKAUFLIN
32       Shanta      Vollman  SVOLLMAN
33        Kevin      Mourgos  KMOURGOS
34        Julia        Nayer    JNAYER
35        Irene  Mikkilineni  IMIKKILI
36        James       Landry   JLANDRY
37       Steven       Markle   SMARKLE
38        Laura       Bissot   LBISSOT
39        Mozhe     Atkinson  MATKINSO
40        James       Marlow   JAMRLOW
41           TJ        Olson   TJOLSON
42        Jason       Mallin   JMALLIN
43      Michael       Rogers   MROGERS
44           Ki          Gee      KGEE
45        Hazel   Philtanker  HPHILTAN
46       Renske       Ladwig   RLADWIG
47      Stephen       Stiles   SSTILES
48         John          Seo      JSEO
49       Joshua        Patel    JPATEL

In [11]:
data.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [12]:
selected_data = data[["FIRST_NAME", "LAST_NAME","EMAIL"]]
display(selected_data)

     FIRST_NAME    LAST_NAME     EMAIL
0        Donald     OConnell  DOCONNEL
1       Douglas        Grant    DGRANT
2      Jennifer       Whalen   JWHALEN
3       Michael    Hartstein  MHARTSTE
4           Pat          Fay      PFAY
5         Susan       Mavris   SMAVRIS
6       Hermann         Baer     HBAER
7       Shelley      Higgins  SHIGGINS
8       William        Gietz    WGIETZ
9        Steven         King     SKING
10        Neena      Kochhar  NKOCHHAR
11          Lex      De Haan   LDEHAAN
12    Alexander       Hunold   AHUNOLD
13        Bruce        Ernst    BERNST
14        David       Austin   DAUSTIN
15        Valli    Pataballa  VPATABAL
16        Diana      Lorentz  DLORENTZ
17        Nancy    Greenberg  NGREENBE
18       Daniel       Faviet   DFAVIET
19         John         Chen     JCHEN
20       Ismael      Sciarra  ISCIARRA
21  Jose Manuel        Urman   JMURMAN
22         Luis         Popp     LPOPP
23          Den     Raphaely  DRAPHEAL
24    Alexander         Khoo     AKHOO
25       Shelli        Baida    SBAIDA
26        Sigal       Tobias   STOBIAS
27          Guy       Himuro   GHIMURO
28        Karen   Colmenares  KCOLMENA
29      Matthew        Weiss    MWEISS
30         Adam        Fripp    AFRIPP
31        Payam     Kaufling  PKAUFLIN
32       Shanta      Vollman  SVOLLMAN
33        Kevin      Mourgos  KMOURGOS
34        Julia        Nayer    JNAYER
35        Irene  Mikkilineni  IMIKKILI
36        James       Landry   JLANDRY
37       Steven       Markle   SMARKLE
38        Laura       Bissot   LBISSOT
39        Mozhe     Atkinson  MATKINSO
40        James       Marlow   JAMRLOW
41           TJ        Olson   TJOLSON
42        Jason       Mallin   JMALLIN
43      Michael       Rogers   MROGERS
44           Ki          Gee      KGEE
45        Hazel   Philtanker  HPHILTAN
46       Renske       Ladwig   RLADWIG
47      Stephen       Stiles   SSTILES
48         John          Seo      JSEO
49       Joshua        Patel    JPATEL

In [13]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/1sgMbcgoOGEDSWu3MDrIcoADW59HZU4ujoLgNBUZJVXg/export?format=csv"
data = pd.read_csv(url)

display(data)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [14]:
data.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20

In [15]:
data.head(10)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90

In [16]:
data.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [17]:
df=data.copy()

In [18]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [19]:
df['EMAIL'].str.lower()

0     doconnel
1       dgrant
2      jwhalen
3     mhartste
4         pfay
5      smavris
6        hbaer
7     shiggins
8       wgietz
9        sking
10    nkochhar
11     ldehaan
12     ahunold
13      bernst
14     daustin
15    vpatabal
16    dlorentz
17    ngreenbe
18     dfaviet
19       jchen
20    isciarra
21     jmurman
22       lpopp
23    drapheal
24       akhoo
25      sbaida
26     stobias
27     ghimuro
28    kcolmena
29      mweiss
30      afripp
31    pkauflin
32    svollman
33    kmourgos
34      jnayer
35    imikkili
36     jlandry
37     smarkle
38     lbissot
39    matkinso
40     jamrlow
41     tjolson
42     jmallin
43     mrogers
44        kgee
45    hphiltan
46     rladwig
47     sstiles
48        jseo
49      jpatel
Name: EMAIL, dtype: object

In [20]:
columns = data.columns.str.capitalize()

In [21]:
df=data.copy()

In [22]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20

In [23]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [25]:
df=df['EMAIL'].str.lower()

In [26]:
df.head()

0    doconnel
1      dgrant
2     jwhalen
3    mhartste
4        pfay
Name: EMAIL, dtype: object

In [27]:
df

0     doconnel
1       dgrant
2      jwhalen
3     mhartste
4         pfay
5      smavris
6        hbaer
7     shiggins
8       wgietz
9        sking
10    nkochhar
11     ldehaan
12     ahunold
13      bernst
14     daustin
15    vpatabal
16    dlorentz
17    ngreenbe
18     dfaviet
19       jchen
20    isciarra
21     jmurman
22       lpopp
23    drapheal
24       akhoo
25      sbaida
26     stobias
27     ghimuro
28    kcolmena
29      mweiss
30      afripp
31    pkauflin
32    svollman
33    kmourgos
34      jnayer
35    imikkili
36     jlandry
37     smarkle
38     lbissot
39    matkinso
40     jamrlow
41     tjolson
42     jmallin
43     mrogers
44        kgee
45    hphiltan
46     rladwig
47     sstiles
48        jseo
49      jpatel
Name: EMAIL, dtype: object

In [28]:
data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [29]:
df = data.copy()

In [30]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [31]:
df = data.copy() # Re-initialize df as a DataFrame
df['EMAIL'] = df['EMAIL'].str.lower()
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,doconnel,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,dgrant,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,jwhalen,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,mhartste,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,pfay,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,smavris,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,hbaer,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,shiggins,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,wgietz,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,sking,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,nkochhar,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,ldehaan,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,ahunold,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,bernst,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,daustin,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,vpatabal,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,dlorentz,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,ngreenbe,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,dfaviet,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,jchen,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,isciarra,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,jmurman,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,lpopp,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,drapheal,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,akhoo,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,sbaida,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,stobias,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,ghimuro,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,kcolmena,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,mweiss,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,afripp,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,pkauflin,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,svollman,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,kmourgos,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,jnayer,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,imikkili,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,jlandry,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,smarkle,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,lbissot,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,matkinso,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,jamrlow,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,tjolson,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,jmallin,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,mrogers,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,kgee,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,hphiltan,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,rladwig,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,sstiles,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,jseo,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,jpatel,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [32]:
df['EMAIL'] = df['EMAIL'].str.lower()
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,doconnel,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,dgrant,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,jwhalen,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,mhartste,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,pfay,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,smavris,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,hbaer,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,shiggins,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,wgietz,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,sking,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,nkochhar,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,ldehaan,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,ahunold,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,bernst,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,daustin,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,vpatabal,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,dlorentz,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,ngreenbe,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,dfaviet,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,jchen,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,isciarra,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,jmurman,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,lpopp,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,drapheal,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,akhoo,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,sbaida,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,stobias,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,ghimuro,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,kcolmena,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,mweiss,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,afripp,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,pkauflin,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,svollman,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,kmourgos,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,jnayer,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,imikkili,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,jlandry,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,smarkle,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,lbissot,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,matkinso,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,jamrlow,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,tjolson,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,jmallin,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,mrogers,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,kgee,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,hphiltan,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,rladwig,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,sstiles,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,jseo,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,jpatel,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [33]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,doconnel,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,dgrant,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,jwhalen,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,mhartste,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,pfay,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,smavris,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,hbaer,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,shiggins,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,wgietz,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,sking,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,nkochhar,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,ldehaan,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,ahunold,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,bernst,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,daustin,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,vpatabal,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,dlorentz,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,ngreenbe,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,dfaviet,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,jchen,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,isciarra,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,jmurman,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,lpopp,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,drapheal,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,akhoo,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,sbaida,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,stobias,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,ghimuro,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,kcolmena,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,mweiss,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,afripp,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,pkauflin,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,svollman,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,kmourgos,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,jnayer,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,imikkili,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,jlandry,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,smarkle,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,lbissot,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,matkinso,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,jamrlow,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,tjolson,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,jmallin,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,mrogers,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,kgee,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,hphiltan,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,rladwig,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,sstiles,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,jseo,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,jpatel,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [34]:
df = data.copy()
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [35]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [36]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20

In [37]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20

In [38]:
df[df["FIRST_NAME"].str.startswith("D")]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30

In [39]:
df['FULL NAME'] = df['FIRST_NAME'] + ' ' + df['LAST_NAME']
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,FULL NAME
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50,Donald OConnell
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50,Douglas Grant
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10,Jennifer Whalen
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20,Michael Hartstein
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20,Pat Fay
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40,Susan Mavris
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70,Hermann Baer
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110,Shelley Higgins
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110,William Gietz
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90,Steven King
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90,Neena Kochhar
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90,Lex De Haan
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60,Alexander Hunold
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60,Bruce Ernst
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60,David Austin
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60,Valli Pataballa
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60,Diana Lorentz
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100,Nancy Greenberg
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100,Daniel Faviet
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100,John Chen
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100,Ismael Sciarra
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100,Jose Manuel Urman
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100,Luis Popp
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30,Den Raphaely
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30,Alexander Khoo
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30,Shelli Baida
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30,Sigal Tobias
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30,Guy Himuro
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30,Karen Colmenares
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50,Matthew Weiss
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50,Adam Fripp
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50,Payam Kaufling
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50,Shanta Vollman
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50,Kevin Mourgos
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50,Julia Nayer
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50,Irene Mikkilineni
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50,James Landry
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50,Steven Markle
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50,Laura Bissot
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50,Mozhe Atkinson
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50,James Marlow
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50,TJ Olson
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50,Jason Mallin
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50,Michael Rogers
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50,Ki Gee
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50,Hazel Philtanker
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50,Renske Ladwig
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50,Stephen Stiles
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50,John Seo
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50,Joshua Patel

In [40]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,FULL NAME
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50,Donald OConnell
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50,Douglas Grant
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10,Jennifer Whalen
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20,Michael Hartstein
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20,Pat Fay

In [41]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,FULL NAME
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50,Donald OConnell
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50,Douglas Grant
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10,Jennifer Whalen
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20,Michael Hartstein
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20,Pat Fay
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40,Susan Mavris
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70,Hermann Baer
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110,Shelley Higgins
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110,William Gietz
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90,Steven King
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90,Neena Kochhar
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90,Lex De Haan
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60,Alexander Hunold
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60,Bruce Ernst
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60,David Austin
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60,Valli Pataballa
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60,Diana Lorentz
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100,Nancy Greenberg
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100,Daniel Faviet
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100,John Chen
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100,Ismael Sciarra
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100,Jose Manuel Urman
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100,Luis Popp
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30,Den Raphaely
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30,Alexander Khoo
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30,Shelli Baida
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30,Sigal Tobias
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30,Guy Himuro
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30,Karen Colmenares
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50,Matthew Weiss
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50,Adam Fripp
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50,Payam Kaufling
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50,Shanta Vollman
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50,Kevin Mourgos
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50,Julia Nayer
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50,Irene Mikkilineni
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50,James Landry
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50,Steven Markle
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50,Laura Bissot
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50,Mozhe Atkinson
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50,James Marlow
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50,TJ Olson
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50,Jason Mallin
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50,Michael Rogers
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50,Ki Gee
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50,Hazel Philtanker
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50,Renske Ladwig
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50,Stephen Stiles
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50,John Seo
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50,Joshua Patel

In [42]:
data = data[data['FIRST_NAME'] != 'Donald']
display(data)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-Dec-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-Jul-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-Nov-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-Aug-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-Jul-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-Apr-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-May-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-Oct-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-Nov-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-Jul-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-Sep-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-Jan-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-Mar-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-Aug-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-Oct-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-Feb-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-Apr-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-Jun-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-Aug-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-Dec-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-Feb-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-Jul-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-Oct-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-Feb-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-Apr-06,ST_CLERK,2500,-,123,50

In [43]:
df1 = df.copy()

In [44]:
df1=df1[['LAST_NAME','FIRST_NAME']]

In [45]:
df1

      LAST_NAME   FIRST_NAME
0      OConnell       Donald
1         Grant      Douglas
2        Whalen     Jennifer
3     Hartstein      Michael
4           Fay          Pat
5        Mavris        Susan
6          Baer      Hermann
7       Higgins      Shelley
8         Gietz      William
9          King       Steven
10      Kochhar        Neena
11      De Haan          Lex
12       Hunold    Alexander
13        Ernst        Bruce
14       Austin        David
15    Pataballa        Valli
16      Lorentz        Diana
17    Greenberg        Nancy
18       Faviet       Daniel
19         Chen         John
20      Sciarra       Ismael
21        Urman  Jose Manuel
22         Popp         Luis
23     Raphaely          Den
24         Khoo    Alexander
25        Baida       Shelli
26       Tobias        Sigal
27       Himuro          Guy
28   Colmenares        Karen
29        Weiss      Matthew
30        Fripp         Adam
31     Kaufling        Payam
32      Vollman       Shanta
33      Mourgos        Kevin
34        Nayer        Julia
35  Mikkilineni        Irene
36       Landry        James
37       Markle       Steven
38       Bissot        Laura
39     Atkinson        Mozhe
40       Marlow        James
41        Olson           TJ
42       Mallin        Jason
43       Rogers      Michael
44          Gee           Ki
45   Philtanker        Hazel
46       Ladwig       Renske
47       Stiles      Stephen
48          Seo         John
49        Patel       Joshua

In [51]:
df1.head(3)

       NAME FIRST_NAME
0  OConnell     Donald
1     Grant    Douglas
2    Whalen   Jennifer

In [53]:
col=df1.pop('NAME')
df1.insert(0,'F_NAME',col)

In [54]:
df1

         F_NAME   FIRST_NAME
0      OConnell       Donald
1         Grant      Douglas
2        Whalen     Jennifer
3     Hartstein      Michael
4           Fay          Pat
5        Mavris        Susan
6          Baer      Hermann
7       Higgins      Shelley
8         Gietz      William
9          King       Steven
10      Kochhar        Neena
11      De Haan          Lex
12       Hunold    Alexander
13        Ernst        Bruce
14       Austin        David
15    Pataballa        Valli
16      Lorentz        Diana
17    Greenberg        Nancy
18       Faviet       Daniel
19         Chen         John
20      Sciarra       Ismael
21        Urman  Jose Manuel
22         Popp         Luis
23     Raphaely          Den
24         Khoo    Alexander
25        Baida       Shelli
26       Tobias        Sigal
27       Himuro          Guy
28   Colmenares        Karen
29        Weiss      Matthew
30        Fripp         Adam
31     Kaufling        Payam
32      Vollman       Shanta
33      Mourgos        Kevin
34        Nayer        Julia
35  Mikkilineni        Irene
36       Landry        James
37       Markle       Steven
38       Bissot        Laura
39     Atkinson        Mozhe
40       Marlow        James
41        Olson           TJ
42       Mallin        Jason
43       Rogers      Michael
44          Gee           Ki
45   Philtanker        Hazel
46       Ladwig       Renske
47       Stiles      Stephen
48          Seo         John
49        Patel       Joshua

In [56]:
display(df[df['SALARY'] > 10000])

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,FULL NAME
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20,Michael Hartstein
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-Jun-02,AC_MGR,12008,-,101,110,Shelley Higgins
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90,Steven King
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90,Neena Kochhar
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90,Lex De Haan
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100,Nancy Greenberg
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-Dec-02,PU_MAN,11000,-,100,30,Den Raphaely

In [58]:
res=len(df[df['SALARY']> 10000])
print("Total employees who has greater than 10k salary:", res)

Total employees who has greater than 10k salary: 7

In [61]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'])
print(df[df['HIRE_DATE'].dt.year == 2025])

Empty DataFrame
Columns: [EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID, FULL NAME]
Index: []

/tmp/ipykernel_225/2418195133.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'])

In [67]:
df1 = df[df['HIRE_DATE'].dt.month_name().str.contains('August')]

In [69]:
df1.head(3)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,FULL NAME
4,202,Pat,Fay,PFAY,603.123.6666,2005-08-17,MK_REP,6000,-,201,20,Pat Fay
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,2002-08-17,FI_MGR,12008,-,101,100,Nancy Greenberg
18,109,Daniel,Faviet,DFAVIET,515.124.4169,2002-08-16,FI_ACCOUNT,9000,-,108,100,Daniel Faviet

In [71]:
df1 = df[df['HIRE_DATE'].dt.year == 2005]

In [72]:
df1.head(3)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,FULL NAME
4,202,Pat,Fay,PFAY,603.123.6666,2005-08-17,MK_REP,6000,-,201,20,Pat Fay
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,-,100,90,Neena Kochhar
14,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,-,103,60,David Austin